Repository grpc/test-infra, pull requests merged in 2020-09, with the labels that each got.

#47 Add missing comma in api/v1/loadtest_types.go
  api/v1/loadtest_types.go
Labels: clean up

#45 Fix incorrect plurality for scenarios env variable
  controllers/loadtest_controller.go
Labels: bug

#44 Use less commonly used ports as defaults
  controllers/suite_test.go
  main.go
Labels: clean up

#43 Setup the ready init container for a driver
  controllers/loadtest_controller.go
  controllers/loadtest_controller_test.go
  pkg/defaults/defaults.go
Labels: enhancement

#46 Fix deployment issues
  .gitignore
  Dockerfile
  config/manager/manager.yaml
  config/rbac/role.yaml
  controllers/loadtest_controller.go
  main.go
Labels: bug

#48 Remove listing of nodes
  controllers/loadtest_controller.go
Labels: bug

#49 Fix anti-affinities for load test pods
  controllers/loadtest_controller.go
Labels: bug

#51 Fix cluster role for listing pods
  config/rbac/role.yaml
  controllers/loadtest_controller.go
Labels: bug

#53 Revise the load test status
  api/v1/loadtest_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/e2etest.grpc.io_loadtests.yaml
Labels: enhancement

#52 Reorganize project, removing pkg and internal directories
  config/certmanager/certificate.yaml
  config/constants.go
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_webhook_patch.yaml
  config/defaults.go
  config/defaults_internal.go
  config/defaults_test.go
  config/manager/manager.yaml
  config/prometheus/monitor.yaml
  config/rbac/bindings/auth_proxy_role_binding.yaml
  config/rbac/bindings/component_role_binding.yaml
  config/rbac/bindings/kustomization.yaml
  config/rbac/bindings/leader_election_role_binding.yaml
  config/rbac/bindings/manager_role_binding.yaml
  config/rbac/kustomization.yaml
  config/rbac/roles/auth_proxy_client_clusterrole.yaml
  config/rbac/roles/auth_proxy_role.yaml
  config/rbac/roles/kustomization.yaml
  config/rbac/roles/leader_election_role.yaml
  config/rbac/roles/loadtest_editor_role.yaml
  config/rbac/roles/loadtest_viewer_role.yaml
  config/rbac/roles/pod_viewer_role.yaml
  config/services/auth_proxy_service.yaml
  config/services/kustomization.yaml
  config/suite_test.go
  config/webhook/service.yaml
  containers/init/ready/ready.go
  controllers/loadtest_controller.go
  controllers/loadtest_controller_test.go
  controllers/suite_test.go
  kubehelpers/auth.go
  main.go
Labels: clean up

#54 Move controller constants to config package
  config/constants.go
  controllers/loadtest_controller.go
  controllers/loadtest_controller_test.go
Labels: clean up

#57 Add optional package with convenience functions
  optional/doc.go
  optional/kubernetes_types.go
  optional/primitive_types.go
Labels: enhancement

#55 Add status package with PodsForLoadTest function
  kubehelpers/auth.go
  status/doc.go
  status/relationships.go
  status/relationships_test.go
  status/suite_test.go
Labels: enhancement

#59 Update the status of a load test and prevent restarts
  api/v1/loadtest_types.go
  controllers/loadtest_controller.go
  status/status.go
  status/status_test.go
Labels: enhancement

#60 Move checkMissingPod func out of controller pkg.
  controllers/loadtest_controller.go
  controllers/loadtest_controller_test.go
  controllers/suite_test.go
  status/missing_pods.go
  status/missing_pods_test.go
  status/suite_test.go
Labels: clean up, low priority

#61 Fix snapshot issue in Dockerfile for driver
  containers/runtime/driver/Dockerfile
Labels: bug

#62 Add python image suporting python 3.7.
  containers/runtime/python/Dockerfile
Labels: enhancement, squash
