Repository grpc/test-infra, pull requests merged in 2020-08, with the labels that each got.

#16 Add ruby image
  containers/runtime/node/Dockerfile
  containers/runtime/ruby/Dockerfile
Labels: enhancement, squash

#12 Add defaults for LoadTests
  api/v1/loadtest_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/e2etest.grpc.io_loadtests.yaml
  config/example_config.yaml
  controllers/loadtest_controller.go
  go.mod
  go.sum
  main.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_internal.go
  pkg/defaults/defaults_suite_test.go
  pkg/defaults/loadtest_defaults.go
  pkg/defaults/loadtest_defaults_test.go
Labels: enhancement

#18 Add load test controller scaffold and test environment
  controllers/loadtest_controller.go
  controllers/loadtest_controller_test.go
  controllers/suite_test.go
Labels: enhancement

#17 Fix code generation comment
  api/v1/loadtest_types.go
Labels: documentation, squash

#15 Add pod creation logic
  controllers/loadtest_controller.go
  controllers/loadtest_controller_test.go
  controllers/suite_test.go
Labels: enhancement, squash

#19 Generate unique component names when unspecified
  pkg/defaults/loadtest_defaults.go
  pkg/defaults/loadtest_defaults_test.go
Labels: enhancement, squash

#20 Add consistent names for containers
  controllers/loadtest_controller.go
  controllers/loadtest_controller_test.go
Labels: enhancement

#22 Build driver code in driver Dockerfile
  containers/runtime/driver/Dockerfile
  containers/runtime/driver/example.json
  containers/runtime/driver/run.sh
Labels: enhancement

#21 Mount volumes with scenarios
  controllers/loadtest_controller.go
  controllers/loadtest_controller_test.go
Labels: enhancement

#26 Update ginkgo to v1.12.0 and gomega to v1.9.0
  go.mod
  go.sum
Labels: enhancement

#25 Add example scenario and load test
  config/samples/README.md
  config/samples/e2etest.grpc.io_v1_loadtest.yaml
  config/samples/java_example_scenario.json
Labels: documentation

#23 Add missing pods logic
  controllers/loadtest_controller.go
  controllers/loadtest_controller_test.go
  controllers/suite_test.go
Labels: enhancement, squash

#30 Fix wrong tag name in defaults
  pkg/defaults/defaults.go
Labels: bug

#29 Set default namespace on load tests and their pods
  controllers/loadtest_controller.go
  controllers/loadtest_controller_test.go
  pkg/defaults/loadtest_defaults.go
  pkg/defaults/loadtest_defaults_test.go
Labels: bug

#27 Add ready init container
  containers/init/ready/Dockerfile
  containers/init/ready/README.md
  containers/init/ready/ready.go
  containers/init/ready/ready_test.go
  containers/init/ready/suite_test.go
  internal/kubehelpers/auth.go
Labels: enhancement, squash

#32 Remove unnecessary logs in Go GitHub Actions
  .github/workflows/go.yml
Labels: low priority

#31 Fix driver issue and refactor defaults package
  controllers/loadtest_controller.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/defaults/loadtest_defaults.go
  pkg/defaults/loadtest_defaults_test.go
Labels: bug

#34 Fix iterator reference issue in defaults package
  pkg/defaults/defaults_internal.go
Labels: bug

#35 Fix issues and simplify example load test YAML file
  config/samples/e2etest.grpc.io_v1_loadtest.yaml
Labels: bug

#36 Create pods when they are missing
  controllers/loadtest_controller.go
Labels: enhancement

#37 Mount a /src/workspace volume in all containers
  controllers/loadtest_controller.go
  controllers/loadtest_controller_test.go
Labels: enhancement

#38 Set build and run working directory to workspace
  controllers/loadtest_controller.go
  controllers/loadtest_controller_test.go
Labels: enhancement, rebase

#39 Use defaults to set ports and port arguments
  controllers/loadtest_controller.go
  controllers/loadtest_controller_test.go
Labels: enhancement

#40 Add worker address file parsing to driver
  containers/runtime/driver/Dockerfile
  containers/runtime/driver/run.sh
Labels: enhancement

#41 Fix issue with overridden workspace in the driver
  containers/runtime/driver/Dockerfile
  containers/runtime/driver/run.sh
Labels: bug
