Repository grpc/test-infra, pull requests merged in 2020-10, with the labels that each got.

#64 Remove skipped test for GCP credentials
  controllers/loadtest_controller_test.go
Labels: clean up

#65 Add support for uploading results to BigQuery
  config/constants.go
  containers/runtime/driver/Dockerfile
  controllers/loadtest_controller.go
  controllers/loadtest_controller_test.go
Labels: enhancement

#66 Add example load test for Java
  config/samples/go_example_loadtest.yaml
  config/samples/java_example_loadtest.yaml
Labels: documentation

#67 Add bazel cache volume
  config/constants.go
  controllers/loadtest_controller.go
  controllers/loadtest_controller_test.go
Labels: bug

#68 Change ready init container timeout to 15 minutes
  containers/init/ready/ready.go
Labels: enhancement

#69 Add container image targets to Makefile
  Makefile
Labels: enhancement

#71 Add example load test and scenario for C++
  config/samples/cxx_example_loadtest.yaml
  config/samples/cxx_example_scenario.json
Labels: documentation

#70 Add example load test for Python
  config/example_config.yaml
  config/samples/python_example_loadtest.yaml
  config/samples/python_example_scenario.json
Labels: documentation, squash

#76 Send quit RPC to terminate workers after test
  containers/runtime/driver/run.sh
Labels: enhancement

#78 Remove container lookups by index
  containers/init/ready/ready_test.go
  controllers/loadtest_controller.go
  controllers/loadtest_controller_test.go
  kubehelpers/pods.go
  kubehelpers/pods_test.go
  kubehelpers/suite_test.go
Labels: clean up
