Repository grpc/test-infra, pull requests merged in 2021-01, with the labels that each got.

#102 Rename cleanup agent test suite
  cleanup/suite_test.go
Labels: clean up

#97 Refactor pod creation logic and add some e2e tests
  api/v1/loadtest_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/e2etest.grpc.io_loadtests.yaml
  config/defaults.go
  config/defaults_test.go
  controllers/loadtest_controller.go
  controllers/loadtest_controller_test.go
  controllers/suite_test.go
  podbuilder/podbuilder.go
  podbuilder/podbuilder_test.go
  podbuilder/suite_test.go
  status/missing_pods.go
  status/status_test.go
  status/suite_test.go
Labels: enhancement

#99 Remove driverPort and serverPort from defaults
  config/constants.go
  config/defaults.go
  config/defaults_template.yaml
  config/defaults_test.go
  controllers/suite_test.go
  podbuilder/podbuilder.go
  podbuilder/podbuilder_test.go
  podbuilder/suite_test.go
Labels: enhancement

#101 Replace default pools with default pool labels
  api/v1/loadtest_types.go
  config/cmd/configure.go
  config/defaults.go
  config/defaults_template.yaml
  config/defaults_test.go
  controllers/loadtest_controller.go
  controllers/loadtest_controller_test.go
  controllers/suite_test.go
  podbuilder/podbuilder.go
  podbuilder/podbuilder_test.go
  podbuilder/suite_test.go
Labels: enhancement

#98 Feature/csharp image
  Makefile
  config/cmd/configure.go
  config/defaults_template.yaml
  config/samples/csharp_example_loadtest.yaml
  containers/init/build/csharp/Dockerfile
  containers/init/build/csharp/build_qps_worker.sh
Labels: enhancement

#90 Add comments and address clone container feedback
  containers/init/clone/clone.sh
Labels: clean up, documentation, release notes: no

#105 Fix status updates when duplicate pods are created
  controllers/loadtest_controller.go
Labels: bug
