Repository grpc/test-infra, pull requests merged in 2021-08, with the labels that each got.

#204 Delete cleanup agent from codebase
  Makefile
  cleanup/cleanup.go
  cleanup/cleanup_test.go
  cleanup/suite_test.go
  cmd/cleanup_agent/main.go
  config/cleanup_agent/cleanup_agent.yaml
  config/cleanup_agent/kustomization.yaml
  containers/runtime/cleanup_agent/Dockerfile
Labels: clean up, release notes: yes

#206 Synchronize kubebuilder3 branch with master.
  Makefile
  cleanup/cleanup.go
  cleanup/cleanup_test.go
  cleanup/suite_test.go
  cmd/cleanup_agent/main.go
  config/cleanup_agent/cleanup_agent.yaml
  config/cleanup_agent/kustomization.yaml
  containers/runtime/cleanup_agent/Dockerfile
Labels: squash

#207 merge master to kubebuilder3 to solve conflicts.
  Makefile
Labels: squash

#210 Fix makefile bug
  Makefile
Labels: bug, release notes: no

#211 Allow go version to be specified for infra build.
  Makefile
Labels: release notes: no

#212 Fail test run when it contains test errors.
  api/v1/zz_generated.deepcopy.go
  tools/cmd/runner/main.go
Labels: release notes: no

#199 Make ready container write out the annotation as JSON
  Makefile
  config/constants.go
  containers/init/ready/ready.go
  containers/runtime/driver/Dockerfile
  containers/runtime/driver/run.sh
  podbuilder/podbuilder.go
Labels: squash, release notes: yes

#213 Add ready-image target back to Makefile
  Makefile
Labels: bug, release notes: no

#214 Shellcheck fixes for shell scripts.
  containers/init/clone/clone.sh
  containers/pre_built_workers/php7/run_protobuf_c_worker.sh
  containers/pre_built_workers/php7/run_worker.sh
  containers/pre_built_workers/php7/run_workers.sh
  containers/runtime/driver/run.sh
  containers/runtime/php7/run_protobuf_c_worker.sh
  containers/runtime/php7/run_worker.sh
Labels: release notes: no

#217 Fix ready container typo
  Makefile
Labels: bug, release notes: no

#216 End xml reports in newline.
  tools/runner/xunit/entities.go
Labels: release notes: no

#218 Make test names in report TestGrid-friendly.
  tools/cmd/runner/main.go
  tools/runner/flags.go
  tools/runner/reporter.go
  tools/runner/xunit/entities.go
  tools/runner/xunit/strings.go
Labels: release notes: yes

#215 save node info to a json file
  config/constants.go
  containers/init/ready/ready.go
  containers/init/ready/ready_test.go
  containers/runtime/driver/run.sh
  podbuilder/podbuilder.go
Labels: squash, release notes: yes
