Repository grpc/test-infra, pull requests merged in 2021-11, with the labels that each got.

#230 Add pod-viewer-role to kustomization.yaml
  config/rbac/kustomization.yaml
Labels: bug, release notes: no

#234 Update PHP7 version for OSS benchmarks images.
  containers/init/build/php7/Dockerfile
  containers/pre_built_workers/php7/Dockerfile
  containers/runtime/php7/Dockerfile
Labels: release notes: yes

#238 Add pod to log filepath map
  tools/runner/logsaver.go
  tools/runner/runner.go
Labels: release notes: no
