Repository grpc/test-infra, pull requests merged in 2021-05, with the labels that each got.

#141 Remove resource quotas for deployments
  config/cleanup_agent/cleanup_agent.yaml
  config/manager/manager.yaml
Labels: bug

#113 Feature/Implement helper scripts for prebuilt workers
  config/samples/cxx_example_loadtest_with_pre_built_workers.yaml
  containers/pre_built_workers/cxx/Dockerfile
  tools/README.md
  tools/delete_prebuilt_workers/delete_prebuilt_workers.go
  tools/prepare_prebuilt_workers/prepare_prebuilt_workers.go
Labels: enhancement, release notes: yes, squash

#130 Feature/Add pre-built go example and Dockerfile
  config/samples/go_example_loadtest_with_pre_built_workers.yaml
  containers/pre_built_workers/go/Dockerfile
Labels: enhancement, release notes: yes

#146 Cleanup delete_prebuilt_workers.go
  tools/delete_prebuilt_workers/delete_prebuilt_workers.go
Labels: clean up, release notes: no

#150 Feature/parallel building
  tools/README.md
  tools/delete_prebuilt_workers/delete_prebuilt_workers.go
  tools/prepare_prebuilt_workers/prepare_prebuilt_workers.go
Labels: enhancement, release notes: yes

#149 Test runner tool.
  Makefile
  cmd/runner/main.go
  go.mod
  tools/runner/client.go
  tools/runner/configs.go
  tools/runner/flags.go
  tools/runner/queues.go
  tools/runner/runner.go
Labels: release notes: yes

#154 Only report status of tests that are not running when it changes
  tools/runner/runner.go
Labels: release notes: no

#153 Update dependencies.
  go.mod
  go.sum
Labels: release notes: no

#155 Log test runner configuration before running tests.
  cmd/runner/main.go
  tools/runner/queues.go
  tools/runner/runner.go
Labels: release notes: no

#156 Fix runner concurrency logic and improve logging.
  tools/runner/runner.go
Labels: release notes: no

#147 Improve images for regular process
  containers/init/build/csharp/build_qps_worker.sh
  containers/init/build/php/build_qps_worker.sh
  containers/init/build/ruby/build_qps_worker.sh
Labels: enhancement, release notes: no

#160 Log details of Kubernetes API errors in the runner
  tools/runner/runner.go
Labels: release notes: yes

#159 Move log messages and reporting out of the test runner.
  cmd/runner/main.go
  tools/runner/flags.go
  tools/runner/queues.go
  tools/runner/reporter.go
  tools/runner/runner.go
Labels: release notes: no

#164 Use "php7" language name in defaults and examples.
  config/defaults_template.yaml
  config/samples/php7_example_loadtest.yaml
  config/samples/php7_example_loadtest_with_pre_built_workers.yaml
  tools/prepare_prebuilt_workers/prepare_prebuilt_workers.go
Labels: release notes: yes

#170 Add all tools as makefile targets.
  Makefile
Labels: release notes: no
