Repository grpc/test-infra, pull requests merged in 2021-04, with the labels that each got.

#121 Add ARG ready container's Dockerfile
  containers/init/ready/Dockerfile
Labels: enhancement

#123 Update Makefile for ready container timeout
  Makefile
Labels: clean up, release notes: no

#135 Delete prototype code.
  benchmarks/Dockerfile
  benchmarks/README.md
  benchmarks/cmd/orchtest/main.go
  benchmarks/cmd/svc/main.go
  benchmarks/cmd/testctl/main.go
  benchmarks/k8s/auth.go
  benchmarks/k8s/images/cxx/Dockerfile
  benchmarks/k8s/images/cxx/run.sh
  benchmarks/k8s/images/driver/Dockerfile
  benchmarks/k8s/images/driver/run.sh
  benchmarks/k8s/images/go/Dockerfile
  benchmarks/k8s/images/go/run.sh
  benchmarks/k8s/images/java/Dockerfile
  benchmarks/k8s/images/java/run.sh
  benchmarks/proto/generate.go
  benchmarks/proto/scheduling/v1/scheduling_service.pb.go
  benchmarks/proto/scheduling/v1/scheduling_service.proto
  benchmarks/svc/operations_server.go
  benchmarks/svc/operations_server_test.go
  benchmarks/svc/orch/controller.go
  benchmarks/svc/orch/controller_test.go
  benchmarks/svc/orch/doc.go
  benchmarks/svc/orch/executor.go
  benchmarks/svc/orch/executor_test.go
  benchmarks/svc/orch/health.go
  benchmarks/svc/orch/internal_test.go
  benchmarks/svc/orch/pod_interfaces.go
  benchmarks/svc/orch/podspec.go
  benchmarks/svc/orch/pool.go
  benchmarks/svc/orch/pool_test.go
  benchmarks/svc/orch/queue.go
  benchmarks/svc/orch/queue_test.go
  benchmarks/svc/orch/reservation.go
  benchmarks/svc/orch/reservation_test.go
  benchmarks/svc/orch/watcher.go
  benchmarks/svc/orch/watcher_test.go
  benchmarks/svc/scheduling_server.go
  benchmarks/svc/scheduling_server_test.go
  benchmarks/svc/store/storage_server.go
  benchmarks/svc/store/storage_server_test.go
  benchmarks/svc/types/component.go
  benchmarks/svc/types/component_test.go
  benchmarks/svc/types/doc.go
  benchmarks/svc/types/event.go
  benchmarks/svc/types/event_test.go
  benchmarks/svc/types/resource_namer.go
  benchmarks/svc/types/session.go
  benchmarks/svc/types/session_test.go
  benchmarks/svc/validator/doc.go
  benchmarks/svc/validator/validator.go
  benchmarks/svc/validator/validator_test.go
  benchmarks/svc/version.go
  go.mod
  go.sum
Labels: release notes: yes

#138 Order languages alphabetically in default template.
  config/defaults_template.yaml
Labels: release notes: no

#136 Trim system paths from binaries.
  Makefile
Labels: release notes: no

#137 Format markdown files.
  CODE-OF-CONDUCT.md
  CONTRIBUTING.md
  README.md
  containers/init/ready/README.md
Labels: release notes: no

#117 Add deadline info to ready container logs
  containers/init/ready/ready.go
Labels: enhancement, release notes: no

#122 Add prebuilt image for nodejs
  Makefile
  config/samples/node_example_loadtest_with_pre_built_workers.yaml
  containers/pre_built_workers/node/Dockerfile
  containers/pre_built_workers/node/build_qps_worker.sh
  containers/pre_built_workers/node/pkg_config.json
Labels: squash
