Repository grpc/test-infra, pull requests merged in 2021-06, with the labels that each got.

#169 Delete references to label "loadtest" from controller.
  cleanup/cleanup_test.go
  config/constants.go
  controllers/loadtest_controller_test.go
  podbuilder/podbuilder.go
  podbuilder/podbuilder_test.go
  status/missing_pods_test.go
  status/relationships.go
  status/relationships_test.go
  status/status_test.go
  status/suite_test.go
Labels: release notes: yes

#174 Update php to php7 in makefile and remaining directory
  Makefile
  containers/init/build/php7/Dockerfile
  containers/init/build/php7/build_qps_worker.sh
Labels: clean up, release notes: no

#173 Use real name instead of uuid
  config/samples/csharp_example_loadtest.yaml
  config/samples/cxx_example_loadtest.yaml
  config/samples/go_example_loadtest.yaml
  config/samples/java_example_loadtest.yaml
  config/samples/node_example_loadtest.yaml
  config/samples/php7_example_loadtest.yaml
  config/samples/python_asyncio_example_loadtest.yaml
  config/samples/python_example_loadtest.yaml
  config/samples/ruby_example_loadtest.yaml
  config/samples/templates/csharp_example_loadtest_with_prebuilt_workers.yaml
  config/samples/templates/cxx_example_loadtest_with_prebuilt_workers.yaml
  config/samples/templates/go_example_loadtest_with_prebuilt_workers.yaml
  config/samples/templates/java_example_loadtest_with_prebuilt_workers.yaml
  config/samples/templates/node_example_loadtest_with_prebuilt_workers.yaml
  config/samples/templates/php7_example_loadtest_with_prebuilt_workers.yaml
  config/samples/templates/python_asyncio_example_loadtest_with_prebuilt_workers.yaml
  config/samples/templates/python_example_loadtest_with_prebuilt_workers.yaml
  config/samples/templates/ruby_example_loadtest_with_prebuilt_workers.yaml
  tools/runner/runner.go
Labels: release notes: yes

#163 Add LoadTest state information to kubectl get
  api/v1/loadtest_types.go
  config/crd/bases/e2etest.grpc.io_loadtests.yaml
Labels: enhancement, release notes: yes

#175 fix envtest
  controllers/loadtest_controller_test.go
Labels: release notes: no

#168 Update README.
  tools/README.md
Labels: clean up, release notes: no

#157 Generate JUnit XML reports in the runner
  cmd/runner/main.go
  tools/runner/junit/doc.go
  tools/runner/junit/entities.go
  tools/runner/junit/strings.go
  tools/runner/reporter.go
  tools/runner/runner.go
Labels: enhancement, release notes: yes

#181 Fix segfault when no XML report is generated
  tools/runner/reporter.go
Labels: bug

#183 Set default test suites name to empty string.
  cmd/runner/main.go
Labels: release notes: yes

#185 Allow uninstall to ignore not found items.
  Makefile
Labels: release notes: no

#186 Update defaults_template.yaml for php7
  config/defaults_template.yaml
Labels: clean up, release notes: no

#189 Update example tests to include named drivers.
  config/samples/csharp_example_loadtest.yaml
  config/samples/cxx_example_loadtest.yaml
  config/samples/go_example_loadtest.yaml
  config/samples/java_example_loadtest.yaml
  config/samples/node_example_loadtest.yaml
  config/samples/php7_example_loadtest.yaml
  config/samples/python_asyncio_example_loadtest.yaml
  config/samples/python_example_loadtest.yaml
  config/samples/ruby_example_loadtest.yaml
Labels: release notes: no

#182 Add timeout for workers
  config/constants.go
  config/samples/csharp_example_loadtest.yaml
  config/samples/cxx_example_loadtest.yaml
  config/samples/go_example_loadtest.yaml
  config/samples/java_example_loadtest.yaml
  config/samples/node_example_loadtest.yaml
  config/samples/php7_example_loadtest.yaml
  config/samples/python_asyncio_example_loadtest.yaml
  config/samples/python_example_loadtest.yaml
  config/samples/ruby_example_loadtest.yaml
  config/samples/templates/csharp_example_loadtest_with_prebuilt_workers.yaml
  config/samples/templates/cxx_example_loadtest_with_prebuilt_workers.yaml
  config/samples/templates/go_example_loadtest_with_prebuilt_workers.yaml
  config/samples/templates/java_example_loadtest_with_prebuilt_workers.yaml
  config/samples/templates/node_example_loadtest_with_prebuilt_workers.yaml
  config/samples/templates/php7_example_loadtest_with_prebuilt_workers.yaml
  config/samples/templates/python_asyncio_example_loadtest_with_prebuilt_workers.yaml
  config/samples/templates/python_example_loadtest_with_prebuilt_workers.yaml
  config/samples/templates/ruby_example_loadtest_with_prebuilt_workers.yaml
  containers/pre_built_workers/php7/run_worker.sh
  containers/runtime/php7/run_worker.sh
  podbuilder/podbuilder.go
  podbuilder/podbuilder_test.go
Labels: enhancement, release notes: yes

#190 Fix executable path in Java Loadtest example with prebuilt image
  config/samples/templates/java_example_loadtest_with_prebuilt_workers.yaml
Labels: bug, release notes: no

#191 Add governance and maintainers files.
  GOVERNANCE.md
  MAINTAINERS.md
Labels: release notes: no

#192 Update driver timeout
  containers/runtime/driver/Dockerfile
  containers/runtime/driver/run.sh
Labels: enhancement

#194 Update README files to include test runner.
  README.md
  containers/runtime/README.md
  tools/README.md
Labels: release notes: no

#196 Move tool binaries under the tools directory.
  Makefile
  tools/README.md
  tools/cmd/delete_prebuilt_workers/main.go
  tools/cmd/prepare_prebuilt_workers/main.go
  tools/cmd/runner/main.go
Labels: release notes: no
