Repository grpc/test-infra, pull requests merged in 2022-11, with the labels that each got.

#327 Update driver version to v1.50.1
  Makefile
Labels: release notes: yes

#329 Fix typo.
  tools/README.md
Labels: release notes: no

#325 Tuning Prometheus' scrapeInterval.
  config/prometheus/install-prometheus.yaml
  config/prometheus/servicemonitors.yaml
Labels: enhancement, release notes: yes

#332 Remove configuration that is not needed.
  config/prometheus/servicemonitors.yaml
Labels: clean up, release notes: yes

#330 Add 20s delay to query using flag.
  containers/runtime/driver/run.sh
Labels: enhancement, release notes: yes

#331 Add documentation for Prometheus scrape interval and query delay.
  config/prometheus/README.md
Labels: documentation, release notes: yes

#333 Pin the driver version.
  Makefile
Labels: release notes: yes

#335 Pin driver version.
  Makefile
Labels: release notes: yes

#336 Update go version to go1.17 everywhere
  config/defaults_template.yaml
  config/defaults_test.go
  containers/init/ready/Dockerfile
  containers/pre_built_workers/go/Dockerfile
  containers/runtime/controller/Dockerfile
  containers/runtime/go/Dockerfile
  containers/runtime/xds-server/Dockerfile
  controllers/suite_test.go
  dashboard/config/postgres_replicator/Dockerfile
  go.mod
  go.sum
  podbuilder/suite_test.go
Labels: release notes: yes
