Repository grpc/test-infra, pull requests merged in 2022-03, with the labels that each got.

#281 Add initial documentation on PSM benchmarks.
  README.md
  config/samples/README.md
  config/samples/templates/psm/README.md
  containers/runtime/xds-server/README.md
  containers/runtime/xds-server/bootstrap.json
  doc/deployment.md
  proto/endpointupdater/endpoint.pb.go
  proto/endpointupdater/endpoint.proto
  proto/endpointupdater/endpoint_grpc.pb.go
Labels: release notes: yes

#283 Fix issue encountered in release process v1.1.0
  containers/runtime/xds-server/Dockerfile
  containers/runtime/xds-server/cmd/main.go
Labels: bug, release notes: no

#284 Fix the xds binary path in psm load test template examples
  config/samples/templates/psm/go_example_loadtest_proxied.yaml
  config/samples/templates/psm/go_example_loadtest_proxyless.yaml
  config/samples/templates/psm/java_example_loadtest_proxied.yaml
  config/samples/templates/psm/java_example_loadtest_proxyless.yaml
Labels: bug, release notes: no

#286 Set default location for PSM images.
  Makefile
  doc/deployment.md
Labels: release notes: yes

#288 Update driver version to v1.45.0.
  Makefile
Labels: release notes: yes

#287 Add complete configuration for prometheus installation.
  config/prometheus/setup/README.md
  config/prometheus/setup/configuration.yaml
  config/prometheus/setup/crds.yaml
  config/prometheus/setup/install-prometheus-operator.yaml
  config/prometheus/setup/install-prometheus.yaml
  config/prometheus/setup/servicemonitors.yaml
Labels: enhancement, release notes: yes
