Repository grpc/test-infra, pull requests merged in 2022-01, with the labels that each got.

#246 Update README.
  README.md
  config/samples/README.md
Labels: documentation, release notes: no

#244 Add dashboard code and configuration
  dashboard/Makefile
  dashboard/cloudbuild.yaml
  dashboard/cmd/postgres_replicator/README.md
  dashboard/cmd/postgres_replicator/config_template.yaml
  dashboard/cmd/postgres_replicator/main.go
  dashboard/config/grafana/Dockerfile
  dashboard/config/grafana/app.yaml
  dashboard/config/grafana/dashboards/default/home.json
  dashboard/config/postgres_replicator/Dockerfile
  dashboard/config/postgres_replicator/app.yaml
  dashboard/config/postgres_replicator/default/config.yaml
  dashboard/grafana/grafana.ini
  dashboard/grafana/provisioning/dashboards/default_provider_config.yaml
  dashboard/grafana/provisioning/datasources/postgres_config.yaml
  dashboard/postgres_replicator/bigquery.go
  dashboard/postgres_replicator/config.go
  dashboard/postgres_replicator/logger.go
  dashboard/postgres_replicator/logger_test.go
  dashboard/postgres_replicator/postgres.go
  dashboard/postgres_replicator/transfer.go
  dashboard/scripts/check_env.sh
  go.mod
  go.sum
Labels: release notes: yes

#248 Apply go mod tidy.
  go.mod
  go.sum
Labels: release notes: no

#247 Format markdown and yaml files.
  .github/workflows/go.yaml
  CONTRIBUTING.md
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/prometheus/monitor.yaml
  config/prometheus/setup/README.md
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/pod_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/README.md
  config/services/kustomization.yaml
  config/webhook/service.yaml
  containers/init/ready/README.md
  dashboard/cloudbuild.yaml
  dashboard/cmd/postgres_replicator/README.md
  dashboard/cmd/postgres_replicator/config_template.yaml
  dashboard/config/grafana/app.yaml
  dashboard/config/postgres_replicator/app.yaml
  dashboard/config/postgres_replicator/default/config.yaml
  dashboard/grafana/provisioning/datasources/postgres_config.yaml
Labels: release notes: no

#245 Marshal and Unmarshal config file of snapshot of xds server
  containers/runtime/xds/config/README.md
  containers/runtime/xds/config/config.go
  containers/runtime/xds/config/config_test.go
  containers/runtime/xds/config/default_config.json
  containers/runtime/xds/config/suite_test.go
  go.mod
  go.sum
Labels: release notes: no

#250 Format JSON files with jq.
  containers/pre_built_workers/node/pkg_config.json
  containers/runtime/driver/example.json
  containers/runtime/xds/config/default_config.json
Labels: clean up, release notes: no

#252 fix dashboard cloudbuild.yaml, README.md
  dashboard/cloudbuild.yaml
  dashboard/cmd/postgres_replicator/README.md
Labels: release notes: no

#253 Fix dashboard cloudbuild.yaml
  dashboard/cloudbuild.yaml
Labels: release notes: no

#254 Fix postgres table name cache issue
  dashboard/postgres_replicator/postgres.go
  dashboard/postgres_replicator/transfer.go
Labels: release notes: no

#242 Add bootstrap file for Envoy
  containers/runtime/bootstrap_Envoy/Dockerfile
  containers/runtime/bootstrap_Envoy/envoy.yaml
Labels: release notes: no

#259 Dashboard fixes
  dashboard/config/grafana/dashboards/default/home.json
Labels: release notes: no

#261 Fix makefile issues caused by the deprecation of `go get`.
  Makefile
  containers/init/build/php7/Dockerfile
Labels: bug, release notes: no

#240 Add pod names to properties
  tools/runner/logsaver.go
  tools/runner/runner.go
Labels: release notes: no

#262 Update base docker images to golang:1.16.
  config/defaults_template.yaml
  config/defaults_test.go
  containers/pre_built_workers/go/Dockerfile
  containers/runtime/go/Dockerfile
  controllers/suite_test.go
  podbuilder/suite_test.go
Labels: release notes: yes

#263 Replace deprecated `go get` with `go install`.
  .github/workflows/go.yaml
  go.mod
  go.sum
Labels: release notes: no
