Repository grpc/test-infra, pull requests merged in 2022-08, with the labels that each got.

#315 Make collection of Prometheus data be controlled by an annotation.
  config/constants.go
  config/samples/templates/psm/cxx_example_loadtest_proxied.yaml
  config/samples/templates/psm/cxx_example_loadtest_proxyless.yaml
  config/samples/templates/psm/go_example_loadtest_proxied.yaml
  config/samples/templates/psm/go_example_loadtest_proxyless.yaml
  config/samples/templates/psm/java_example_loadtest_proxied.yaml
  config/samples/templates/psm/java_example_loadtest_proxyless.yaml
  config/samples/templates/psm/node_example_loadtest_proxied.yaml
  config/samples/templates/psm/node_example_loadtest_proxyless.yaml
  config/samples/templates/psm/php7_example_loadtest_proxied.yaml
  config/samples/templates/psm/php7_example_loadtest_proxyless.yaml
  config/samples/templates/psm/php7_protobuf_c_example_loadtest_proxied.yaml
  config/samples/templates/psm/php7_protobuf_c_example_loadtest_proxyless.yaml
  config/samples/templates/psm/prebuilt/cxx_example_loadtest_proxied_with_prebuilt_workers.yaml
  config/samples/templates/psm/prebuilt/cxx_example_loadtest_proxyless_with_prebuilt_workers.yaml
  config/samples/templates/psm/prebuilt/go_example_loadtest_proxied_with_prebuilt_workers.yaml
  config/samples/templates/psm/prebuilt/go_example_loadtest_proxyless_with_prebuilt_workers.yaml
  config/samples/templates/psm/prebuilt/java_example_loadtest_proxied_with_prebuilt_workers.yaml
  config/samples/templates/psm/prebuilt/java_example_loadtest_proxyless_with_prebuilt_workers.yaml
  config/samples/templates/psm/prebuilt/node_example_loadtest_proxied_with_prebuilt_workers.yaml
  config/samples/templates/psm/prebuilt/node_example_loadtest_proxyless_with_prebuilt_workers.yaml
  config/samples/templates/psm/prebuilt/php7_example_loadtest_proxied_with_prebuilt_workers.yaml
  config/samples/templates/psm/prebuilt/php7_example_loadtest_proxyless_with_prebuilt_workers.yaml
  config/samples/templates/psm/prebuilt/php7_protobuf_c_example_loadtest_proxied_with_prebuilt_workers.yaml
  config/samples/templates/psm/prebuilt/php7_protobuf_c_example_loadtest_proxyless_with_prebuilt_workers.yaml
  config/samples/templates/psm/prebuilt/python_asyncio_example_loadtest_proxied_with_prebuilt_workers.yaml
  config/samples/templates/psm/prebuilt/python_asyncio_example_loadtest_proxyless_with_prebuilt_workers.yaml
  config/samples/templates/psm/prebuilt/python_example_loadtest_proxied_with_prebuilt_workers.yaml
  config/samples/templates/psm/prebuilt/python_example_loadtest_proxyless_with_prebuilt_workers.yaml
  config/samples/templates/psm/python_asyncio_example_loadtest_proxied.yaml
  config/samples/templates/psm/python_asyncio_example_loadtest_proxyless.yaml
  config/samples/templates/psm/python_example_loadtest_proxied.yaml
  config/samples/templates/psm/python_example_loadtest_proxyless.yaml
  containers/runtime/driver/Dockerfile
  containers/runtime/driver/run.sh
  kubehelpers/psm.go
  podbuilder/podbuilder.go
Labels: release notes: yes

#317 Add PSM dashboard to OSS benchmark dashboard.
  dashboard/Makefile
  dashboard/README.md
  dashboard/cloudbuild.yaml
  dashboard/config/grafana/dashboards/psm/psm.json
  dashboard/config/postgres_replicator/psm/config.yaml
  status/missing_pods_test.go
Labels: release notes: yes

#318 Update documentation for using annotation: enablePrometheus to enable Prometheus.
  README.md
  config/prometheus/README.md
  config/samples/README.md
  dashboard/README.md
Labels: documentation, release notes: no

#319 Only copy the dashboard file to the output directory.
  dashboard/Makefile
Labels: bug, release notes: no

#320 Format fixes.
  dashboard/README.md
  tools/README.md
Labels: documentation, release notes: no
