Repository grpc/test-infra, pull requests merged in 2023-05, with the labels that each got.

#349 Update build image for cxx and python images.
  config/defaults_template.yaml
  containers/pre_built_workers/cxx/Dockerfile
  containers/pre_built_workers/python/Dockerfile
  containers/runtime/driver/Dockerfile
Labels: bug, release notes: yes

#350 Update obsolete actions and go version.
  .github/workflows/go.yaml
Labels: clean up, release notes: no

#357 Update dockerfile for prebuilt Python workers.
  containers/pre_built_workers/python/Dockerfile
Labels: bug, release notes: yes

#351 Update dockerfile for prebuilt C++ workers.
  containers/pre_built_workers/cxx/Dockerfile
Labels: bug, release notes: yes

#358 Fix typo.
  containers/pre_built_workers/python/Dockerfile
Labels: bug, release notes: no

#361 Update driver version to v1.53.1.
  Makefile
Labels: clean up, release notes: yes

#360 Update driver base images.
  containers/runtime/driver/Dockerfile
Labels: bug, release notes: no

#362 Update dependencies and set compatibility to go1.17
  go.mod
  go.sum
Labels: clean up, release notes: yes, dependencies

#365 Add note on PSM dashboard configuration.
  dashboard/README.md
Labels: documentation, release notes: no

#364 Update the prepare_prebuilt_workers to be able to specify repo.
  tools/README.md
  tools/cmd/prepare_prebuilt_workers/main.go
Labels: enhancement, release notes: yes
